[package]
name = "mcaptcha-cli"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"

[dependencies]
pow_sha256 = "0.2"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1"
clipboard = "0.5"
clap = "2.33"
